/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JGBasePrograms;

import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author manue
 */
public class LoginWindow extends javax.swing.JFrame {

    //Conexion BDD
    private connect conexion;

    //Variables int
    int xMouse, yMouse;

    /**
     * Creates new form LoginWindow
     */
    Queries query = new Queries();

    public LoginWindow() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PhotoLogo = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginBTNPanel = new javax.swing.JPanel();
        LoginBTNLabel = new javax.swing.JLabel();
        WindowBar = new javax.swing.JPanel();
        ClosePanel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        RegisterLabel = new javax.swing.JLabel();

        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(0, 8, 20));
        BG.setName(""); // NOI18N
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Logo.png"))); // NOI18N
        BG.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 300, 270));

        PhotoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/City.png"))); // NOI18N
        PhotoLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        BG.add(PhotoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 300, 500));

        LoginLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginLabel.setText("INICIO DE SESIÓN:");
        BG.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 340, 90));

        NameLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Nombre:");
        BG.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 40));

        NameField.setBackground(new java.awt.Color(18, 30, 50));
        NameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NameField.setForeground(new java.awt.Color(153, 153, 153));
        NameField.setText("Ingresar nombre...");
        NameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NameFieldMousePressed(evt);
            }
        });
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        BG.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 420, 40));

        PasswordLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Contraseña:");
        BG.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 40));

        PasswordField.setBackground(new java.awt.Color(18, 30, 50));
        PasswordField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordField.setText("********");
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldMousePressed(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        BG.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 420, 40));

        LoginBTNPanel.setBackground(new java.awt.Color(18, 30, 50));
        LoginBTNPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        LoginBTNLabel.setBackground(new java.awt.Color(18, 30, 50));
        LoginBTNLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LoginBTNLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginBTNLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginBTNLabel.setText("Iniciar sesión");
        LoginBTNLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBTNLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBTNLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBTNLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBTNLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginBTNPanelLayout = new javax.swing.GroupLayout(LoginBTNPanel);
        LoginBTNPanel.setLayout(LoginBTNPanelLayout);
        LoginBTNPanelLayout.setHorizontalGroup(
            LoginBTNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBTNPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LoginBTNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginBTNPanelLayout.setVerticalGroup(
            LoginBTNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBTNPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LoginBTNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(LoginBTNPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 320, 50));

        WindowBar.setBackground(new java.awt.Color(0, 8, 20));
        WindowBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                WindowBarMouseDragged(evt);
            }
        });
        WindowBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WindowBarMousePressed(evt);
            }
        });

        ClosePanel.setBackground(new java.awt.Color(0, 8, 20));
        ClosePanel.setForeground(new java.awt.Color(0, 8, 20));

        CloseLabel.setBackground(new java.awt.Color(0, 8, 20));
        CloseLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        CloseLabel.setForeground(new java.awt.Color(255, 255, 255));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("X");
        CloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ClosePanelLayout = new javax.swing.GroupLayout(ClosePanel);
        ClosePanel.setLayout(ClosePanelLayout);
        ClosePanelLayout.setHorizontalGroup(
            ClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ClosePanelLayout.setVerticalGroup(
            ClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClosePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout WindowBarLayout = new javax.swing.GroupLayout(WindowBar);
        WindowBar.setLayout(WindowBarLayout);
        WindowBarLayout.setHorizontalGroup(
            WindowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WindowBarLayout.createSequentialGroup()
                .addComponent(ClosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 770, Short.MAX_VALUE))
        );
        WindowBarLayout.setVerticalGroup(
            WindowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WindowBarLayout.createSequentialGroup()
                .addComponent(ClosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BG.add(WindowBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));

        RegisterLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterLabel.setText("¿Aún no tienes cuenta? Regístrate.");
        RegisterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseExited(evt);
            }
        });
        BG.add(RegisterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 320, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WindowBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WindowBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_WindowBarMousePressed

    private void WindowBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WindowBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_WindowBarMouseDragged

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        ClosePanel.setBackground(Color.red);
        CloseLabel.setForeground(Color.black);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        ClosePanel.setBackground(new Color(0, 8, 20));
        CloseLabel.setForeground(Color.white);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void LoginBTNLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBTNLabelMouseEntered
        LoginBTNPanel.setBackground(new Color(50, 60, 80));
    }//GEN-LAST:event_LoginBTNLabelMouseEntered

    private void LoginBTNLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBTNLabelMouseExited
        LoginBTNPanel.setBackground(new Color(18, 30, 50));
    }//GEN-LAST:event_LoginBTNLabelMouseExited

    private void NameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameFieldMousePressed
        if (NameField.getText().equals("Ingresar nombre...")) {
            NameField.setText("");
            NameField.setForeground(Color.white);
        }
        if (String.valueOf(PasswordField.getPassword()).isEmpty()) {
            PasswordField.setText("********");
            PasswordField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_NameFieldMousePressed

    private void PasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMousePressed
        if (String.valueOf(PasswordField.getPassword()).equals("********")) {
            PasswordField.setText("");
            PasswordField.setForeground(Color.white);
        }
        if (NameField.getText().isEmpty()) {
            NameField.setText("Ingresar nombre...");
            NameField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_PasswordFieldMousePressed

    private void LoginBTNLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBTNLabelMouseClicked
        
        String nombreUsuario = NameField.getText(); // Obtén el nombre de usuario ingresado
        String contrasena = new String(PasswordField.getPassword()); // Obtén la contraseña ingresada
        boolean credencialesValidas = query.verificarCredenciales(nombreUsuario, contrasena);
        if (credencialesValidas) {
            new SearchWindow().setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Intento de login fallido");
        }
    }//GEN-LAST:event_LoginBTNLabelMouseClicked

    private void RegisterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseClicked
        String nombreUsuario = NameField.getText(); // Obtén el nombre de usuario ingresado
        String contrasena = new String(PasswordField.getPassword()); // Obtén la contraseña ingresada
        if (nombreUsuario.length()<10){
            showMessageDialog(null,"El nombre de usuario debe tener al menos 10 caracteres.");
        }
        else if (contrasena.length()<10){
            showMessageDialog(null,"La contraseña debe tener al menos 10 caracteres.");
        } else {           
            query.Registrarse(nombreUsuario,contrasena);
        }
        
    }//GEN-LAST:event_RegisterLabelMouseClicked

    private void RegisterLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseEntered
        RegisterLabel.setForeground(new Color(67, 188, 224));
    }//GEN-LAST:event_RegisterLabelMouseEntered

    private void RegisterLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseExited
        RegisterLabel.setForeground(Color.white);
    }//GEN-LAST:event_RegisterLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JPanel ClosePanel;
    private javax.swing.JLabel LoginBTNLabel;
    private javax.swing.JPanel LoginBTNPanel;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PhotoLogo;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JPanel WindowBar;
    // End of variables declaration//GEN-END:variables
}
