/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JGBasePrograms;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manue
 */
public class SearchWindow extends javax.swing.JFrame {

    int xMouse, yMouse;
    Queries query = new Queries();
    private String gen;
    private String legendario;
    private String tipo1;
    private String tipo2;
    private String Nombre;
    
    int ID;
    private String Nombre_Agregar;
    private boolean Legendario_Agregar;
    private int Gen_Agregar;
    private String Tipo1_Agregar;
    private String Tipo2_Agregar;
    

    public String condLegendario(String opcionLegendario) {
        switch (opcionLegendario) {
            case "No":
                return " WHERE legendario=false";
            case "Sí":
                return " WHERE legendario=true";
            default:
                return " WHERE legendario IS NOT NULL";
        }
    }

    public String condTipo1(String opcionTipo1) {
        if (opcionTipo1.equals("-")) {
            return " AND Tipo1 IS NOT NULL";
        } else {
            return " AND Tipo1='" + opcionTipo1 + "'";
        }
    }

    public String condTipo2(String opcionTipo2) {
        if (opcionTipo2.equals("-")) {
            return "";
        } else {
            return " AND Tipo2='" + opcionTipo2 + "'";
        }
    }

    public String condGen(String opcionGen) {
        switch (opcionGen) {
            case "Gen I":
                return " AND Gen=1";
            case "Gen II":
                return " AND Gen=2";
            case "Gen III":
                return " AND Gen=3";
            case "Gen IV":
                return " AND Gen=4";
            case "Gen V":
                return " AND Gen=5";
            case "Gen VI":
                return " AND Gen=6";
            case "Gen VII":
                return " AND Gen=7";
            case "Gen VIII":
                return " AND Gen=8";
            case "Gen IX":
                return " AND Gen=9";
            default:
                return " AND Gen IS NOT NULL";
        }
    }

    public int Gen_agregar(String opcionGen) {
        switch (opcionGen) {
            case "Gen I":
                return 1;
            case "Gen II":
                return 2;
            case "Gen III":
                return 3;
            case "Gen IV":
                return 4;
            case "Gen V":
                return 5;
            case "Gen VI":
                return 6;
            case "Gen VII":
                return 7;
            case "Gen VIII":
                return 8;
            case "Gen IX":
                return 9;
            default:
                return 0;
        }
        
    }
    
    public boolean Legendario_agregar(String opcionLegendario){
        switch (opcionLegendario) {
            case "No":
                return false;
            case "Sí":
                return true;
            default:
                return false;
        }
    }
    
    
        /**
         * Creates new form SearchWindow
         */
    public SearchWindow() {
        initComponents();
    }

    public DefaultTableModel VisualizarTablas(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Núm. Pokédex");
        model.addColumn("Nombre");
        model.addColumn("Tipo 1");
        model.addColumn("Tipo 2");
        model.addColumn("Legendario");
        model.addColumn("Generación");
        model.addColumn("Sprite");
        PKMNTableList.setModel(model);
        return model;
    }
    
    public void BuscarPKMN(String Legendario, String Gen, String Tipo1, String Tipo2, String Nombre) {
        DefaultTableModel model = VisualizarTablas();
        query.MostrarResultadosTabla(model, Legendario, Gen, Tipo1, Tipo2, Nombre);

    }

    public void AgregarPKMN(int ID, String Nombre, String Tipo1, String Tipo2, boolean Legendario, int Gen) {        
        query.AgregarPKMN(ID, Nombre, Tipo1, Tipo2, Legendario, Gen);        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        LabelJGBasePKMN = new javax.swing.JLabel();
        LegendarioLabel = new javax.swing.JLabel();
        JSearchBar = new javax.swing.JTextField();
        JSearchLogo = new javax.swing.JLabel();
        SearchBarLabel = new javax.swing.JLabel();
        JComboLegendario = new javax.swing.JComboBox<>();
        Tipo2Label = new javax.swing.JLabel();
        JComboTipo2 = new javax.swing.JComboBox<>();
        GenLabel = new javax.swing.JLabel();
        JComboGen = new javax.swing.JComboBox<>();
        Tipo1Label = new javax.swing.JLabel();
        JComboTipo1 = new javax.swing.JComboBox<>();
        JWindowBar = new javax.swing.JPanel();
        JClosePanel = new javax.swing.JPanel();
        JCloseLabel = new javax.swing.JLabel();
        ButtonSearchPanel = new javax.swing.JPanel();
        ButtonSearchLabel = new javax.swing.JLabel();
        ButtonDeletePanel = new javax.swing.JPanel();
        ButtonDeleteLabel = new javax.swing.JLabel();
        ButtonAddPanel = new javax.swing.JPanel();
        ButtonAddLabel = new javax.swing.JLabel();
        PKMNTablePanel = new javax.swing.JScrollPane();
        PKMNTableList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(35, 38, 56));
        BG.setForeground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJGBasePKMN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJGBasePKMN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/JGBasePKMNLogo.png"))); // NOI18N
        BG.add(LabelJGBasePKMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -40, 900, 300));

        LegendarioLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LegendarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        LegendarioLabel.setText("Legendario:");
        BG.add(LegendarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 130, 50));

        JSearchBar.setBackground(new java.awt.Color(27, 30, 52));
        JSearchBar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        JSearchBar.setForeground(new java.awt.Color(255, 255, 255));
        BG.add(JSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 720, 50));

        JSearchLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/searching.png"))); // NOI18N
        BG.add(JSearchLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        SearchBarLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        SearchBarLabel.setForeground(new java.awt.Color(255, 255, 255));
        SearchBarLabel.setText("Buscar nombre:");
        BG.add(SearchBarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 50));

        JComboLegendario.setBackground(new java.awt.Color(54, 54, 63));
        JComboLegendario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JComboLegendario.setForeground(new java.awt.Color(255, 255, 255));
        JComboLegendario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Sí", "No" }));
        JComboLegendario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboLegendarioItemStateChanged(evt);
            }
        });
        JComboLegendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboLegendarioActionPerformed(evt);
            }
        });
        BG.add(JComboLegendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 170, 30));

        Tipo2Label.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Tipo2Label.setForeground(new java.awt.Color(255, 255, 255));
        Tipo2Label.setText("Seleccionar tipo 2:");
        BG.add(Tipo2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, 50));

        JComboTipo2.setBackground(new java.awt.Color(54, 54, 63));
        JComboTipo2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JComboTipo2.setForeground(new java.awt.Color(255, 255, 255));
        JComboTipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Normal", "Fuego", "Planta", "Agua", "Tierra", "Veneno", "Roca", "Lucha", "Eléctrico", "Bicho", "Volador", "Acero", "Hielo", "Siniestro", "Fantasma", "Psíquico", "Hada", "Dragón" }));
        JComboTipo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboTipo2ItemStateChanged(evt);
            }
        });
        JComboTipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboTipo2ActionPerformed(evt);
            }
        });
        BG.add(JComboTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 200, 30));

        GenLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        GenLabel.setForeground(new java.awt.Color(255, 255, 255));
        GenLabel.setText("Seleccionar generación:");
        BG.add(GenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 50));

        JComboGen.setBackground(new java.awt.Color(54, 54, 63));
        JComboGen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JComboGen.setForeground(new java.awt.Color(255, 255, 255));
        JComboGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Gen I", "Gen II", "Gen III", "Gen IV", "Gen V", "Gen VI", "Gen VII", "Gen VIII", "Gen IX" }));
        JComboGen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboGenItemStateChanged(evt);
            }
        });
        JComboGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboGenActionPerformed(evt);
            }
        });
        BG.add(JComboGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 200, 30));

        Tipo1Label.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Tipo1Label.setForeground(new java.awt.Color(255, 255, 255));
        Tipo1Label.setText("Seleccionar tipo 1:");
        BG.add(Tipo1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, 50));

        JComboTipo1.setBackground(new java.awt.Color(54, 54, 63));
        JComboTipo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JComboTipo1.setForeground(new java.awt.Color(255, 255, 255));
        JComboTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Normal", "Fuego", "Planta", "Agua", "Tierra", "Veneno", "Roca", "Lucha", "Eléctrico", "Bicho", "Volador", "Acero", "Hielo", "Siniestro", "Fantasma", "Psíquico", "Hada", "Dragón" }));
        JComboTipo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboTipo1ItemStateChanged(evt);
            }
        });
        JComboTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboTipo1ActionPerformed(evt);
            }
        });
        BG.add(JComboTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 200, 30));

        JWindowBar.setBackground(new java.awt.Color(35, 38, 56));
        JWindowBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JWindowBarMouseDragged(evt);
            }
        });
        JWindowBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JWindowBarMousePressed(evt);
            }
        });

        JClosePanel.setBackground(new java.awt.Color(35, 38, 56));
        JClosePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JCloseLabel.setBackground(new java.awt.Color(35, 38, 56));
        JCloseLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        JCloseLabel.setForeground(new java.awt.Color(255, 255, 255));
        JCloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JCloseLabel.setText("X");
        JCloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JCloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JCloseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JClosePanelLayout = new javax.swing.GroupLayout(JClosePanel);
        JClosePanel.setLayout(JClosePanelLayout);
        JClosePanelLayout.setHorizontalGroup(
            JClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JCloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );
        JClosePanelLayout.setVerticalGroup(
            JClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JCloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JWindowBarLayout = new javax.swing.GroupLayout(JWindowBar);
        JWindowBar.setLayout(JWindowBarLayout);
        JWindowBarLayout.setHorizontalGroup(
            JWindowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JWindowBarLayout.createSequentialGroup()
                .addComponent(JClosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 991, Short.MAX_VALUE))
        );
        JWindowBarLayout.setVerticalGroup(
            JWindowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JClosePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BG.add(JWindowBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 70));

        ButtonSearchPanel.setBackground(new java.awt.Color(27, 30, 52));
        ButtonSearchPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        ButtonSearchPanel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSearchPanel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        ButtonSearchLabel.setBackground(new java.awt.Color(27, 30, 52));
        ButtonSearchLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        ButtonSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSearchLabel.setText("Buscar...");
        ButtonSearchLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSearchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonSearchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonSearchPanelLayout = new javax.swing.GroupLayout(ButtonSearchPanel);
        ButtonSearchPanel.setLayout(ButtonSearchPanelLayout);
        ButtonSearchPanelLayout.setHorizontalGroup(
            ButtonSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );
        ButtonSearchPanelLayout.setVerticalGroup(
            ButtonSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        BG.add(ButtonSearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 380, 60));

        ButtonDeletePanel.setBackground(new java.awt.Color(27, 30, 52));
        ButtonDeletePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ButtonDeletePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonDeletePanelMouseEntered(evt);
            }
        });

        ButtonDeleteLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ButtonDeleteLabel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDeleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonDeleteLabel.setText("Quitar...");
        ButtonDeleteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonDeleteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDeleteLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonDeleteLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonDeleteLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonDeletePanelLayout = new javax.swing.GroupLayout(ButtonDeletePanel);
        ButtonDeletePanel.setLayout(ButtonDeletePanelLayout);
        ButtonDeletePanelLayout.setHorizontalGroup(
            ButtonDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonDeleteLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        ButtonDeletePanelLayout.setVerticalGroup(
            ButtonDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonDeleteLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        BG.add(ButtonDeletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 180, 60));

        ButtonAddPanel.setBackground(new java.awt.Color(27, 30, 52));
        ButtonAddPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        ButtonAddLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ButtonAddLabel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonAddLabel.setText("Agregar...");
        ButtonAddLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAddLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAddLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAddLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonAddPanelLayout = new javax.swing.GroupLayout(ButtonAddPanel);
        ButtonAddPanel.setLayout(ButtonAddPanelLayout);
        ButtonAddPanelLayout.setHorizontalGroup(
            ButtonAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ButtonAddPanelLayout.setVerticalGroup(
            ButtonAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        BG.add(ButtonAddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, 60));

        PKMNTableList.setForeground(new java.awt.Color(0, 0, 0));
        PKMNTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        PKMNTableList.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                PKMNTableListComponentRemoved(evt);
            }
        });
        PKMNTablePanel.setViewportView(PKMNTableList);

        BG.add(PKMNTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 1010, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JWindowBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JWindowBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_JWindowBarMousePressed

    private void JWindowBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JWindowBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_JWindowBarMouseDragged

    private void JCloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JCloseLabelMouseClicked

    private void JCloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseLabelMouseEntered
        JClosePanel.setBackground(Color.red);
        JCloseLabel.setForeground(Color.black);
    }//GEN-LAST:event_JCloseLabelMouseEntered

    private void JCloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseLabelMouseExited
        JClosePanel.setBackground(new Color(35, 38, 56));
        JCloseLabel.setForeground(Color.white);
    }//GEN-LAST:event_JCloseLabelMouseExited

    private void ButtonSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSearchLabelMouseClicked
        Nombre = " AND Nombre LIKE '" + JSearchBar.getText() + "%'";
        BuscarPKMN(legendario, gen, tipo1, tipo2, Nombre);
    }//GEN-LAST:event_ButtonSearchLabelMouseClicked

    private void ButtonSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSearchLabelMouseEntered
        ButtonSearchPanel.setBackground(new Color(52, 60, 80));
    }//GEN-LAST:event_ButtonSearchLabelMouseEntered

    private void ButtonSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSearchLabelMouseExited
        ButtonSearchPanel.setBackground(new Color(27, 30, 52));
    }//GEN-LAST:event_ButtonSearchLabelMouseExited

    private void ButtonDeletePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeletePanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDeletePanelMouseEntered

    private void ButtonDeleteLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteLabelMouseEntered
        ButtonDeletePanel.setBackground(new Color(52, 60, 80));
    }//GEN-LAST:event_ButtonDeleteLabelMouseEntered

    private void ButtonDeleteLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteLabelMouseExited
        ButtonDeletePanel.setBackground(new Color(27, 30, 52));
    }//GEN-LAST:event_ButtonDeleteLabelMouseExited

    private void ButtonDeleteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteLabelMouseClicked

        DefaultTableModel dtm = (DefaultTableModel) PKMNTableList.getModel();
        if (PKMNTableList.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningún Pokémon para borrar.");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha borrado el registro de la lista del Pokémon seleccionado.");
            dtm.removeRow(PKMNTableList.getSelectedRow());
        }
        
    }//GEN-LAST:event_ButtonDeleteLabelMouseClicked

    private void ButtonAddLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddLabelMouseClicked
         
        ID = query.getValorID();
        Nombre_Agregar = JSearchBar.getText();
        AgregarPKMN(ID, Nombre_Agregar, Tipo1_Agregar, Tipo2_Agregar, Legendario_Agregar, Gen_Agregar);
        
    }//GEN-LAST:event_ButtonAddLabelMouseClicked

    private void ButtonAddLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddLabelMouseEntered
        ButtonAddPanel.setBackground(new Color(52, 60, 80));
    }//GEN-LAST:event_ButtonAddLabelMouseEntered

    private void ButtonAddLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddLabelMouseExited
        ButtonAddPanel.setBackground(new Color(27, 30, 52));
    }//GEN-LAST:event_ButtonAddLabelMouseExited

    private void JComboTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboTipo1ActionPerformed

    }//GEN-LAST:event_JComboTipo1ActionPerformed

    private void JComboGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboGenActionPerformed

    }//GEN-LAST:event_JComboGenActionPerformed

    private void JComboTipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboTipo2ActionPerformed

    }//GEN-LAST:event_JComboTipo2ActionPerformed

    private void JComboLegendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboLegendarioActionPerformed

    }//GEN-LAST:event_JComboLegendarioActionPerformed

    private void JComboGenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboGenItemStateChanged
        String opcionGen = JComboGen.getSelectedItem().toString();

        gen = condGen(opcionGen);
        Gen_Agregar = Gen_agregar(opcionGen);

    }//GEN-LAST:event_JComboGenItemStateChanged

    private void JComboLegendarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboLegendarioItemStateChanged
        String opcionLegendario = JComboLegendario.getSelectedItem().toString();

        legendario = condLegendario(opcionLegendario);
        Legendario_Agregar = Legendario_agregar(opcionLegendario);

    }//GEN-LAST:event_JComboLegendarioItemStateChanged

    private void JComboTipo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboTipo1ItemStateChanged
        String opcionTipo1 = JComboTipo1.getSelectedItem().toString();

        tipo1 = condTipo1(opcionTipo1);
        Tipo1_Agregar = opcionTipo1;
        

    }//GEN-LAST:event_JComboTipo1ItemStateChanged

    private void JComboTipo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboTipo2ItemStateChanged
        String opcionTipo2 = JComboTipo2.getSelectedItem().toString();

        tipo2 = condTipo2(opcionTipo2);
        Tipo2_Agregar = opcionTipo2;

    }//GEN-LAST:event_JComboTipo2ItemStateChanged

    private void PKMNTableListComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PKMNTableListComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_PKMNTableListComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel ButtonAddLabel;
    private javax.swing.JPanel ButtonAddPanel;
    private javax.swing.JLabel ButtonDeleteLabel;
    private javax.swing.JPanel ButtonDeletePanel;
    private javax.swing.JLabel ButtonSearchLabel;
    private javax.swing.JPanel ButtonSearchPanel;
    private javax.swing.JLabel GenLabel;
    private javax.swing.JLabel JCloseLabel;
    private javax.swing.JPanel JClosePanel;
    private javax.swing.JComboBox<String> JComboGen;
    private javax.swing.JComboBox<String> JComboLegendario;
    private javax.swing.JComboBox<String> JComboTipo1;
    private javax.swing.JComboBox<String> JComboTipo2;
    private javax.swing.JTextField JSearchBar;
    private javax.swing.JLabel JSearchLogo;
    private javax.swing.JPanel JWindowBar;
    private javax.swing.JLabel LabelJGBasePKMN;
    private javax.swing.JLabel LegendarioLabel;
    private javax.swing.JTable PKMNTableList;
    private javax.swing.JScrollPane PKMNTablePanel;
    private javax.swing.JLabel SearchBarLabel;
    private javax.swing.JLabel Tipo1Label;
    private javax.swing.JLabel Tipo2Label;
    // End of variables declaration//GEN-END:variables
}
